Linux packer
AnzhiZhang/CurseForgeModpackDownloader pull request #1
Opened 2022-05-23 10:39 UTC by choulily

2022-05-23 10:42 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +    name: Build Package for Windows
linux打包为什么叫这个名字？

2022-05-23 10:59 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +
这里仍然使用 stepts，跨job是否可行？

2022-05-23 10:59 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +
```suggesstion
application/exe
```

2022-05-23 11:01 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +          asset_content_type: application/zip
```suggestion
          asset_content_type: application/octet-stream
```

```

2022-05-23 11:02 UTC, AnzhiZhang commented
建议linux可以直接源码运行

2022-05-23 11:02 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +          prerelease: ${{ github.event.inputs.pre_release }}
tag重复无法创建release

2022-05-23 12:02 UTC, AnzhiZhang requested changes

2022-05-23 12:02 UTC, AnzhiZhang commented on .github/workflows/release.yml
>            asset_content_type: application/zip
顺便改了
```suggestion
          asset_content_type: application/vnd.microsoft.portable-executable
```

2022-05-23 12:03 UTC, AnzhiZhang commented
请先解决已标记的问题

2022-05-23 13:51 UTC, AnzhiZhang commented
请好了之后再打开

2022-05-23 22:38 UTC, choulily commented
上述问题均已解决 最新版本的打包姬已经可以使用 [actions](https://github.com/choulily/MinecraftModpackDownloader-LinuxBuild/actions/runs/2374316726) [Release](https://github.com/choulily/MinecraftModpackDownloader-LinuxBuild/releases/tag/1.114514)

2022-06-10 15:57 UTC, AnzhiZhang commented
Will be closed at 2022.6.12.

2022-06-10 15:59 UTC, AnzhiZhang commented
请解决玩问题及时将 Draft 改为 Open，你这样我都不知道，还以为不改了。
现在使用了 release-please，请解决冲突

2022-06-10 16:01 UTC, AnzhiZhang commented
冲突解决提示：先将 master merge 到你的分支，然后解决修改，把 linux packer 移到第二个 job 即可

2022-06-18 23:46 UTC, closed without merging