INDEV-New Linux Compile Script
AnzhiZhang/CurseForgeModpackDownloader pull request #22
Opened 2022-06-19 02:29 UTC by choulily

添加了为linux平台的打包姬

2022-06-19 09:04 UTC, AnzhiZhang commented
我记得我使用了一些linux不支持的窗口特性，还是建议linux直接使用源码而不是特意打包

2022-06-19 09:07 UTC, AnzhiZhang commented
完成后请移除 `.gitignore`、`CHANGELOG.mc` 和 `README.md` 的更改，在服务器打包不需要考虑 gitignore

2022-06-19 10:14 UTC, choulily commented
我注意到这个高dpi缩放的问题了(还好我打开看了看)，注释掉后源码运行，tk还会报icon的错，不知道为什么，icon注释掉运行不报错了但窗口弹不出来
运行了但又没运行
![gif1](https://s1.328888.xyz/2022/06/19/0KK2Q.gif)
对应上个图片的源码
![img1](https://s1.328888.xyz/2022/06/19/0Kaj4.png)
高dpi缩放报错
![0Kn9B.png](https://s1.328888.xyz/2022/06/19/0Kn9B.png)
tk的icon报错
![0KvoZ.png](https://s1.328888.xyz/2022/06/19/0KvoZ.png)

2022-06-19 10:25 UTC, choulily commented
我把去掉高dpi的源码放到我仓库上跑一遍编译看看

2022-06-19 10:40 UTC, AnzhiZhang commented
icon 可能是运行时获取临时路径的问题，linux可能这个特性不支持

2022-06-19 12:39 UTC, choulily commented
用print(PATH.TEMP_DIR_PATH)是可以获取到临时路径的

2022-06-19 12:54 UTC, choulily commented
淦，高dpi注释多了，然后那个SXvscode把缩进搞乱了,不看源码我估计这辈子也查不出来，icon很不幸还是不能带
现在完美*运行
![0aAGe.png](https://s1.328888.xyz/2022/06/19/0aAGe.png)

*不是很完美，unzip还有虫，八成是临时目录，一看都没有临时目录

2022-06-19 13:01 UTC, choulily commented
![0alMS.png](https://s1.328888.xyz/2022/06/19/0alMS.png)

2022-06-20 00:35 UTC, choulily commented
现在是·真·完美运行
![0FxfX.png](https://s1.328888.xyz/2022/06/20/0FxfX.png)

2022-06-20 00:36 UTC, choulily commented
再加一些判断windows上该有的功能也可以用了

2022-06-20 02:43 UTC, choulily commented
VSCode净干好事
![0ZQSF.png](https://s1.328888.xyz/2022/06/20/0ZQSF.png)
![0ZA77.png](https://s1.328888.xyz/2022/06/20/0ZA77.png)

2022-06-20 03:14 UTC, AnzhiZhang reviewed
1. Gitignore 删多了
2. CHANGELOG 也删多了
3. 跨平台的判断我觉得不太优雅。图标能否在 constants 如果为linux则设置为 None，iconbitmap() 支持传入 None，不希望到处 import platform。utils.window 两个类只有高DPI的区别，做 if 判断用原来一个类的方式

2022-06-20 03:14 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +          pull-request-title-pattern: "chore${scope}: 🔖 release${component} ${version}"
请勿改为双引号

2022-06-20 03:14 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +    name: Pack on Windows and Upload Artifact&Release
我不想要 artifact

2022-06-20 03:14 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +          python-version: "3.10"
请勿改为双引号

2022-06-20 03:14 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +      - name: Upload to Release
我不想要 artifact

2022-06-20 03:14 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +          python-version: "3.10"
请勿改为双引号

2022-06-20 03:14 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +        run: python -m pip install --upgrade pip && pip install -r requirements.txt
安装依赖指令保持一致

2022-06-20 03:14 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +          path: dist/pack.tar.gz
我不想要 artifact

2022-06-20 03:14 UTC, AnzhiZhang commented on README.md
> +
不要

2022-06-20 03:14 UTC, AnzhiZhang commented on main.py
> +# It Seems Run It Via Code It Is A Lot Faster Than The Packed Version? Am I Wrong?
注释没删，而且确实源码更快，因为打包文件需要先解压准备环境

2022-06-20 03:14 UTC, AnzhiZhang commented on main.py
> +from re import I
注释没删，re的这个import也没用

2022-06-20 03:14 UTC, AnzhiZhang commented on main.py
> +    # It Seems Temp Folder Works , But I Don't Where It is Probably /tmp?
注释没删

2022-06-20 03:14 UTC, AnzhiZhang commented on main.py
> +    # It Seems Temp Folder Works , But I Don't Where It is Probably /tmp?
在软件相同目录，没有使用系统的temp

2022-06-20 03:14 UTC, AnzhiZhang commented on utils/constant.py
> +    # Actually Temp Dir Works ,But The Floder Is Not There, A Little Bit Confusing
注释没删，linux可能在 ~/ ？

2022-06-20 03:14 UTC, AnzhiZhang commented on utils/constant.py
> +
请勿移除

2022-06-20 03:26 UTC, choulily commented on utils/constant.py
> +
oh 我没想起来我注释了这个

2022-06-20 03:57 UTC, choulily commented
上述问题均已更改

2022-06-20 04:12 UTC, AnzhiZhang requested changes
CHANGELOG 和 gitignore 还是没有还原

2022-06-20 04:12 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +      - name: Upload to Release
```suggestion
      - name: Upload to Release Asset
```

2022-06-20 04:12 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +    name: Pack on Windows and Upload Release
```suggestion
    name: Pack on Windows and Upload
```

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/main.py
> +
多了一行

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/main.py
> +        # High DPI On Windows
```suggestion
        # High DPI on Windows
```

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/main.py
> +            ()
else 可以不要

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/main.py
> +    ()
import 移到主类的判断里面吧，import platform 应该在上面 sys 之后

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/download.py
> +
多了一行

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/frames/show.py
> +
多了一行

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/frames/filters.py
> +from re import I
没有用到的 import，移除

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/frames/show.py
> +                    target=run, name=f'Get Modpack Versions ({_id})').start()
这个没超 80 字，你IDE是不是设成最多 79 了

2022-06-20 04:12 UTC, AnzhiZhang commented on utils/window/__init__.py
>  ]
这个文件不要改了，别的导入的地方也没改，没意义

2022-06-20 04:12 UTC, AnzhiZhang commented on .github/workflows/release.yml
> -  pack:
多删了一行

2022-06-20 04:32 UTC, AnzhiZhang commented on utils/constant.py
> +    if(platform.system() == 'Windows'):
python 的语法不需要括号
```suggestion
    if platform.system() == 'Windows':
```

2022-06-20 04:32 UTC, AnzhiZhang commented on CHANGELOG.md
> -# Changelog
这个CHANGELOG 删多了

2022-06-20 04:32 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +
多了俩空格

2022-06-20 04:32 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +      - name: Upload to Release Asset
标题性质的名称，没必要加 to
```suggestion
      - name: Upload Release Asset
```

2022-06-20 04:40 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +          asset_content_type: application/x-compressed-tar
https://en.wikipedia.org/wiki/List_of_archive_formats#:~:text=txz%2C%20.tar.zst-,application/x%2Dgtar,-tar%20with%20gzip
```suggestion
          asset_content_type: application/x-gtar
```

2022-06-20 05:27 UTC, AnzhiZhang approved these changes
其它的都没有问题了，懒得测试，您再测试一下没问题我就合并了

2022-06-20 05:27 UTC, AnzhiZhang commented on .github/workflows/release.yml
> +    name: Pack on Linux and Upload Release
```suggestion
    name: Pack on Linux and Upload
```

2022-06-20 05:49 UTC, AnzhiZhang commented on utils/constant.py
> +    if platform.system() == 'Windows'：
```suggestion
    if platform.system() == 'Windows':
```

2022-06-20 06:06 UTC, choulily commented
![0vW0P.png](https://s1.328888.xyz/2022/06/20/0vW0P.png)

2022-06-20 06:25 UTC, merged

2022-06-20 06:28 UTC, AnzhiZhang commented
提醒一下，你本地 git 的用户名和邮箱没改